# Generated by Django 4.1.7 on 2023-03-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='سن')),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='m', max_length=30, verbose_name='جنسیت')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیو گرافی')),
                ('is_admin', models.BooleanField(default=False, verbose_name='آیا کاربر ادمین است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا کاربر فعال است؟')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
